// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2024_airbnb_herkansing.Data;

#nullable disable

namespace _2024_airbnb_herkansing.Migrations
{
    [DbContext(typeof(_2024_airbnb_herkansingContext))]
    [Migration("20240325144447_ninth_migration")]
    partial class ninth_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2024_airbnb_herkansing.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId");

                    b.HasIndex("ReservationId")
                        .IsUnique()
                        .HasFilter("[ReservationId] IS NOT NULL");

                    b.ToTable("Customer");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "jamesjamerson@gmail.com",
                            FirstName = "James",
                            LastName = "Jamerson"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "emilyboberson@gmail.com",
                            FirstName = "Emily",
                            LastName = "Boberson"
                        });
                });

            modelBuilder.Entity("_2024_airbnb_herkansing.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsCover")
                        .HasColumnType("bit");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.ToTable("Image");

                    b.HasData(
                        new
                        {
                            ImageId = 1,
                            Description = "Avatar of Landlord 1",
                            IsCover = true,
                            Url = "avatar_landlord_2.jpg"
                        },
                        new
                        {
                            ImageId = 2,
                            Description = "Avatar of Landlord 2",
                            IsCover = true,
                            Url = "avatar_landlord_2.jpg"
                        },
                        new
                        {
                            ImageId = 3,
                            Description = "Image of location 1",
                            IsCover = true,
                            Url = "image_location_1.jpg"
                        },
                        new
                        {
                            ImageId = 4,
                            Description = "Image of location 2",
                            IsCover = true,
                            Url = "image_location_2.jpg"
                        });
                });

            modelBuilder.Entity("_2024_airbnb_herkansing.Models.Landlord", b =>
                {
                    b.Property<int>("LandlordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LandlordId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("LandlordId");

                    b.HasIndex("ImageId");

                    b.HasIndex("LocationId");

                    b.ToTable("Landlord");

                    b.HasData(
                        new
                        {
                            LandlordId = 1,
                            Age = 35,
                            FirstName = "Landlord 1",
                            LastName = "Lastname 1"
                        },
                        new
                        {
                            LandlordId = 2,
                            Age = 45,
                            FirstName = "Landlord 2",
                            LastName = "Lastname 2"
                        });
                });

            modelBuilder.Entity("_2024_airbnb_herkansing.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Features")
                        .HasColumnType("int");

                    b.Property<int?>("ImageId")
                        .HasColumnType("int");

                    b.Property<int?>("LanlordId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfGuests")
                        .HasColumnType("int");

                    b.Property<float>("PricePerDay")
                        .HasColumnType("real");

                    b.Property<int?>("ReservationId")
                        .HasColumnType("int");

                    b.Property<int>("Rooms")
                        .HasColumnType("int");

                    b.Property<string>("SubTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("LocationId");

                    b.HasIndex("ImageId");

                    b.HasIndex("LanlordId")
                        .IsUnique()
                        .HasFilter("[LanlordId] IS NOT NULL");

                    b.HasIndex("ReservationId");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Description = "De camping ligt verscholen achter de boerderij in de polder. Op fietsafstand (5 minuten) liggen het dorpje Nieuwvliet, de zee, het strand, het bos van Erasmus en het natuurgebied de Knokkert.",
                            Features = 4,
                            NumberOfGuests = 2,
                            PricePerDay = 100f,
                            Rooms = 1,
                            SubTitle = "Lekker veel ruimte",
                            Title = "De Boerenhoeve",
                            Type = 1
                        },
                        new
                        {
                            LocationId = 2,
                            Description = "Description 4",
                            Features = 4,
                            NumberOfGuests = 2,
                            PricePerDay = 100f,
                            Rooms = 1,
                            SubTitle = "Subtitle 4",
                            Title = "Location 2",
                            Type = 0
                        });
                });

            modelBuilder.Entity("_2024_airbnb_herkansing.Models.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ReservationId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("LocationId")
                        .IsUnique()
                        .HasFilter("[LocationId] IS NOT NULL");

                    b.ToTable("Reservation");

                    b.HasData(
                        new
                        {
                            ReservationId = 1,
                            Discount = 0f,
                            EndDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            StartDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            ReservationId = 2,
                            Discount = 0f,
                            EndDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Local),
                            StartDate = new DateTime(2024, 3, 26, 0, 0, 0, 0, DateTimeKind.Local)
                        });
                });

            modelBuilder.Entity("_2024_airbnb_herkansing.Models.Customer", b =>
                {
                    b.HasOne("_2024_airbnb_herkansing.Models.Reservation", "Reservations")
                        .WithOne()
                        .HasForeignKey("_2024_airbnb_herkansing.Models.Customer", "ReservationId");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("_2024_airbnb_herkansing.Models.Landlord", b =>
                {
                    b.HasOne("_2024_airbnb_herkansing.Models.Image", "Avatar")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("_2024_airbnb_herkansing.Models.Location", "Locations")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("Avatar");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("_2024_airbnb_herkansing.Models.Location", b =>
                {
                    b.HasOne("_2024_airbnb_herkansing.Models.Image", "Images")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.HasOne("_2024_airbnb_herkansing.Models.Landlord", "Landlord")
                        .WithOne()
                        .HasForeignKey("_2024_airbnb_herkansing.Models.Location", "LanlordId");

                    b.HasOne("_2024_airbnb_herkansing.Models.Reservation", "Reservations")
                        .WithMany()
                        .HasForeignKey("ReservationId");

                    b.Navigation("Images");

                    b.Navigation("Landlord");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("_2024_airbnb_herkansing.Models.Reservation", b =>
                {
                    b.HasOne("_2024_airbnb_herkansing.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("_2024_airbnb_herkansing.Models.Location", "Location")
                        .WithOne()
                        .HasForeignKey("_2024_airbnb_herkansing.Models.Reservation", "LocationId");

                    b.Navigation("Customer");

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
